data:
  # baseUrl: http://maps-by-decade-data.dev/
  baseUrl: http://localhost:52831/

cssVariables:
  mobileWidth: 800px
  backgroundColor: '#fefefe'
  textColor: '#333'
  mainColor: '#aed8e6'
  mapColor: '#d7ecf3'

mapOptions:
  singleDecade:
    map:
      zoomControl: true
      scrollWheelZoom: true
      doubleClickZoom: true
      boxZoom: true
      keyboard: true
      minZoom: 10
      maxZoom: 18
      attributionControl: false
      zoom: 13
      center: [40.75319,-73.98224]
      maxBounds: [[40.436495, -73.424377], [41.155910, -74.347229]]
    tileLayer:
      opacity: 0.4
      tileUrl: https://api.mapbox.com/styles/v1/nypllabs/ciqs7cs9w0000cwm74gb05xmq/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoibnlwbGxhYnMiLCJhIjoiSFVmbFM0YyJ9.sl0CRaO71he1XMf_362FZQ
    geojson:
      color: '#39484c'
      weight: 1.5
      opacity: 0.7
      fillOpacity: 0
    geojsonSelected:
      color: '#39484c'
      fillColor: white
      weight: 3
      opacity: 1
      fillOpacity: 0.2
  miniMap:
    map:
      zoomControl: false
      scrollWheelZoom: false
      doubleClickZoom: false
      keyboard: true
      boxZoom: false
      minZoom: 10
      maxZoom: 10
      attributionControl: false
      zoom: 10
      center: [40.75319,-73.98224]
      # With maxBounds enabled Leaflet.Sync is hangs browser when moving one
      #   out of set bounds
      # maxBounds: [[40.436495, -73.424377], [41.155910, -74.347229]]
    tileLayer:
      opacity: 0.6
      tileUrl: https://api.mapbox.com/styles/v1/nypllabs/ciqs7ai4a0000cwm4663mv4x7/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoibnlwbGxhYnMiLCJhIjoiSFVmbFM0YyJ9.sl0CRaO71he1XMf_362FZQ
    geojson:
      color: '#39484c'
      weight: 1.5
      opacity: 0.7
      fillOpacity: 0
    geojsonSelected:
      color: '#39484c'
      fillColor: white
      weight: 3
      opacity: 1
      fillOpacity: 0.2
